src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: BookingRepository::class)]
class Booking
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'date')]
    /**
     * @Assert\NotNull
     * @Assert\Range(
     *      min = "now",
     *      max = "+1 years"
     * )
     */
    private $start_date;

    #[ORM\Column(type: 'date')]
    /**
     * @Assert\NotNull
     * @Assert\Expression(
     *     "this.getEndDate() >= this.getStartDate()",
     *     message="This value couldn't be before start date"
     * )
     */
    private $end_date;

    #[ORM\ManyToOne(targetEntity: Property::class, inversedBy: 'bookings')]
    #[ORM\JoinColumn(nullable: false)]
    private $property;

    #[ORM\Column(type: 'integer')]
    /**
     * @Assert\Positive
     */
    private $nb_guest;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $comment;

    #[ORM\Column(type: 'string', length: 50)]
    private $status='inquiry';

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getProperty(): ?Property
    {
        return $this->property;
    }

    public function setProperty(?Property $property): self
    {
        $this->property = $property;

        return $this;
    }

    public function getNbGuest(): ?int
    {
        return $this->nb_guest;
    }

    public function setNbGuest(int $nb_guest): self
    {
        $this->nb_guest = $nb_guest;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class BookingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('start_date',DateType::class,[
                'widget' => 'choice',
                'years' => [date('Y'),date('Y')+1],
            ])
            ->add('end_date',DateType::class,[
                'widget' => 'choice',
                'years' => [date('Y'),date('Y')+1],
            ])
            ->add('nb_guest')
            ->add('comment')
            ->add('status')
            ->add('property')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Form\BookingType;
use App\Repository\BookingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/booking')]
class BookingController extends AbstractController
{
    private $category = 'Booking';
    #[Route('/', name: 'app_booking_index', methods: ['GET'])]
    public function index(BookingRepository $bookingRepository): Response
    {
        return $this->render('back/booking/index.html.twig', [
            'bookings' => $bookingRepository->findAll(),
            'pageBC' => 'List',
            'categoryBC' => $this->category,
        ]);
    }

    #[Route('/new', name: 'app_booking_new', methods: ['GET', 'POST'])]
    public function new(Request $request, BookingRepository $bookingRepository): Response
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bookingRepository->add($booking, true);

            return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/booking/new.html.twig', [
            'booking' => $booking,
            'form' => $form,
            'pageBC' => 'Index',
            'categoryBC' => $this->category,
        ]);
    }

    #[Route('/{id}', name: 'app_booking_show', methods: ['GET'])]
    public function show(Booking $booking): Response
    {
        return $this->render('back/booking/show.html.twig', [
            'booking' => $booking,
            'pageBC' => 'Index',
            'categoryBC' => $this->category,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_booking_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Booking $booking, BookingRepository $bookingRepository): Response
    {
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bookingRepository->add($booking, true);

            return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/booking/edit.html.twig', [
            'booking' => $booking,
            'form' => $form,
            'pageBC' => 'Index',
            'categoryBC' => $this->category,
        ]);
    }

    #[Route('/{id}', name: 'app_booking_delete', methods: ['POST'])]
    public function delete(Request $request, Booking $booking, BookingRepository $bookingRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$booking->getId(), $request->request->get('_token'))) {
            $bookingRepository->remove($booking, true);
        }

        return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/back/booking/_delete_form.html.twig
<form method="post" action="{{ path('app_booking_delete', {'id': booking.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ booking.id) }}">
    <button class="btn">Delete</button>
</form>

templates/back/booking/edit.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Edit Booking{% endblock %}

{% block body %}
    <h1>Edit Booking</h1>

    {{ include('back/booking/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_booking_index') }}">back to list</a>

    {{ include('back/booking/_delete_form.html.twig') }}
{% endblock %}

templates/back/booking/index.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Booking index{% endblock %}

{% block body %}
    <h1>Booking index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Start_date</th>
                <th>End_date</th>
                <th>Nb_guest</th>
                <th>Comment</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for booking in bookings %}
            <tr>
                <td>{{ booking.id }}</td>
                <td>{{ booking.startDate ? booking.startDate|date('Y-m-d') : '' }}</td>
                <td>{{ booking.endDate ? booking.endDate|date('Y-m-d') : '' }}</td>
                <td>{{ booking.nbGuest }}</td>
                <td>{{ booking.comment }}</td>
                <td>{{ booking.status }}</td>
                <td>
                    <a href="{{ path('app_booking_show', {'id': booking.id}) }}">show</a>
                    <a href="{{ path('app_booking_edit', {'id': booking.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_booking_new') }}">Create new</a>
{% endblock %}

templates/back/booking/new.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}New Booking{% endblock %}

{% block body %}
    <h1>Create new Booking</h1>

    {{ include('back/booking/_form.html.twig') }}

    <a href="{{ path('app_booking_index') }}">back to list</a>
{% endblock %}

templates/back/booking/show.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Booking{% endblock %}

{% block body %}
    <h1>Booking</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ booking.id }}</td>
            </tr>
            <tr>
                <th>Start_date</th>
                <td>{{ booking.startDate ? booking.startDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>End_date</th>
                <td>{{ booking.endDate ? booking.endDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nb_guest</th>
                <td>{{ booking.nbGuest }}</td>
            </tr>
            <tr>
                <th>Comment</th>
                <td>{{ booking.comment }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ booking.status }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_booking_index') }}">back to list</a>

    <a href="{{ path('app_booking_edit', {'id': booking.id}) }}">edit</a>

    {{ include('booking/_delete_form.html.twig') }}
{% endblock %}