src/Entity/Property.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PropertyRepository::class)]
class Property
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 200)]
    /**
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 5,
     *      max = 200,
     *      minMessage = "Your title must be at least {{ limit }} characters long",
     *      maxMessage = "Your title cannot be longer than {{ limit }} characters"
     * )
     */
    private $title;

    #[ORM\Column(type: 'text')]
    /**
     * @Assert\NotBlank
     */
    private $description;

    #[ORM\Column(type: 'integer')]
    /**
     * @Assert\Type(
     *     type="integer",
     *     message="The value {{ value }} is not a valid {{ type }}."
     * )
     * @Assert\Positive
     */
    private $bedrooms;

    #[ORM\Column(type: 'float')]
    private $min_price;

    #[ORM\Column(type: 'string', length: 50)]
    private $type;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $pool;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $gym;

    #[ORM\OneToMany(mappedBy: 'property', targetEntity: Picture::class,cascade: ['persist'])]
    private $pictures;

    #[ORM\OneToMany(mappedBy: 'property', targetEntity: Booking::class)]
    private $bookings;

    #[ORM\OneToMany(mappedBy: 'property', targetEntity: Price::class)]
    #[ORM\OrderBy(["start_date" => "ASC"])]
    private $prices;

    #[ORM\OneToOne(targetEntity: Picture::class, cascade: ['persist', 'remove'])]
    private $main_picture;

    public array $priceList=[];

    #[ORM\Column(type: 'string', length: 50)]
    private $status;
    public function __construct()
    {
        $this->pictures = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->prices = new ArrayCollection();
    }
    public function __toString()
    {
        return $this->title;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getMinPrice(): ?float
    {
        return $this->min_price;
    }

    public function setMinPrice(float $min_price): self
    {
        $this->min_price = $min_price;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {

        $this->type = $type;

        return $this;
    }

    public function getPool(): ?string
    {
        return $this->pool;
    }

    public function setPool(?string $pool): self
    {
        $this->pool = $pool;

        return $this;
    }

    public function getGym(): ?string
    {
        return $this->gym;
    }

    public function setGym(?string $gym): self
    {
        $this->gym = $gym;

        return $this;
    }

    /**
     * @return Collection<int, Picture>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProperty($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setProperty($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getProperty() === $this) {
                $booking->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Price>
     */
    public function getPrices(): Collection
    {
        return $this->prices;
    }

    public function addPrice(Price $price): self
    {
        if (!$this->prices->contains($price)) {
            $this->prices[] = $price;
            $price->setProperty($this);
        }

        return $this;
    }

    public function removePrice(Price $price): self
    {
        if ($this->prices->removeElement($price)) {
            // set the owning side to null (unless already changed)
            if ($price->getProperty() === $this) {
                $price->setProperty(null);
            }
        }

        return $this;
    }

    public function getMainPicture(): ?Picture
    {
        return $this->main_picture;
    }

    public function setMainPicture(?Picture $main_picture): self
    {
        $this->main_picture = $main_picture;

        return $this;
    }

    public function setPriceList($startDate,$endDate):self
    {
        $prices = $this->getPrices();
        $this->priceList = array();
        $currentDate = new \DateTime($startDate->format('Y-m-d H:i:s'));
        while($currentDate<$endDate){
            $this->priceList[$currentDate->format('Y-m-d')] =
                $this->getMinPrice();
            foreach($prices as $price){
                if ($currentDate >= $price->getStartDate() && $currentDate <= $price->getEndDate()) {
                    $this->priceList[$currentDate->format('Y-m-d')] =$price->getPrice();
                    break;
                }
            }
            $currentDate->modify('+1 day');
        }
        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Entity/Settings.php
<?php

namespace App\Entity;

use App\Repository\SettingsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SettingsRepository::class)]
class Settings
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $logo;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $landing_title;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $landing_text;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $SocialFB;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $socialTwitter;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $socialLinkedIn;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $socialInsta;

    #[ORM\OneToMany(mappedBy: 'landing_slider', targetEntity: Picture::class)]
    private $landing_slider_picture;

    #[ORM\Column(type: 'string', length: 10, nullable: true)]
    private $currency;

    public function __construct()
    {
        $this->landing_slider_picture = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getLandingTitle(): ?string
    {
        return $this->landing_title;
    }

    public function setLandingTitle(?string $landing_title): self
    {
        $this->landing_title = $landing_title;

        return $this;
    }

    public function getLandingText(): ?string
    {
        return $this->landing_text;
    }

    public function setLandingText(?string $landing_text): self
    {
        $this->landing_text = $landing_text;

        return $this;
    }

    public function getSocialFB(): ?string
    {
        return $this->SocialFB;
    }

    public function setSocialFB(?string $SocialFB): self
    {
        $this->SocialFB = $SocialFB;

        return $this;
    }

    public function getSocialTwitter(): ?string
    {
        return $this->socialTwitter;
    }

    public function setSocialTwitter(?string $socialTwitter): self
    {
        $this->socialTwitter = $socialTwitter;

        return $this;
    }

    public function getSocialLinkedIn(): ?string
    {
        return $this->socialLinkedIn;
    }

    public function setSocialLinkedIn(?string $socialLinkedIn): self
    {
        $this->socialLinkedIn = $socialLinkedIn;

        return $this;
    }

    public function getSocialInsta(): ?string
    {
        return $this->socialInsta;
    }

    public function setSocialInsta(?string $socialInsta): self
    {
        $this->socialInsta = $socialInsta;

        return $this;
    }

    /**
     * @return Collection<int, picture>
     */
    public function getLandingSliderPicture(): Collection
    {
        return $this->landing_slider_picture;
    }

    public function addLandingSliderPicture(picture $landingSliderPicture): self
    {
        if (!$this->landing_slider_picture->contains($landingSliderPicture)) {
            $this->landing_slider_picture[] = $landingSliderPicture;
            $landingSliderPicture->setLandingSlider($this);
        }

        return $this;
    }

    public function removeLandingSliderPicture(picture $landingSliderPicture): self
    {
        if ($this->landing_slider_picture->removeElement($landingSliderPicture)) {
            // set the owning side to null (unless already changed)
            if ($landingSliderPicture->getLandingSlider() === $this) {
                $landingSliderPicture->setLandingSlider(null);
            }
        }

        return $this;
    }

    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    public function setCurrency(?string $currency): self
    {
        $this->currency = $currency;

        return $this;
    }
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Entity\Page;
use App\Entity\Property;
use App\Entity\Settings;
use App\Form\AvailabilityType;
use App\Repository\PageRepository;
use App\Repository\PropertyRepository;
use App\Repository\SettingsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\DateTime;


class FrontController extends AbstractController
{
    #[Route('/', name: 'app_front')]
    public function index(SettingsRepository $settingsRepository, PageRepository $pageRepository, PropertyRepository $propertyRepository, Request $request): Response
    {
        //TODO : get only the title of all pages, we dont need all datas
        $pages = $pageRepository->findAll();
        $properties = $propertyRepository->findAll();
        $settings = $settingsRepository->find(1);
        $form=$this->createForm(AvailabilityType::class);
        $searchDates=[];
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $searchDates['start']= $form->get('start_date')->getData();
            $searchDates['end'] = $form->get('end_date')->getData();
            foreach ($properties as $property){
                $property->setPriceList($searchDates['start'],$searchDates['end']);
            }
        }
        dump($properties);

        return $this->renderForm('front/base.html.twig', [
            'controller_name' => 'FrontController',
            'settings'=>$settings,
            'pages'=>$pages,
            'properties' => $properties,
            'availability_form' => $form,
            'searchDates' => $searchDates,
        ]);
    }
    #[Route('/page/{title}', name: 'front_pages_show')]
    public function page(SettingsRepository $settingsRepository, PageRepository $pageRepository, PropertyRepository $propertyRepository,Page $page,int $id=1): Response
    {
        $pages = $pageRepository->findAll();
        $properties = $propertyRepository->findAll();
        $settings = $settingsRepository->find($id);
//        TODO:link to right template, and create the template
        return $this->render('front/pages/page.html.twig', [
            'controller_name' => 'FrontController',
            'settings' => $settings,
            'page' => $page,
            'pages' => $pages,
            'properties' => $properties,
        ]);
    }
    #[Route('/property/{id}', name: 'front_property_show')]
    public function property(SettingsRepository $settingsRepository, PageRepository $pageRepository,PropertyRepository $propertyRepository,Property $property): Response
    {
        $settings = $settingsRepository->find(1);
        $pages = $pageRepository->findAll();
        $properties = $propertyRepository->findAll();
        return $this->render('front/property/details.html.twig', [
            'controller_name' => 'FrontController',
            'settings' => $settings,
            'property' => $property,
            'pages' => $pages,
            'properties' => $properties,
        ]);
    }
}

templates/front/section/_featuredproperties.html.twig
<!-- Gallery Section Start -->
<section class="gallery-section" id="gallery">
    <div class=" text-center gallery-carousel owl-carousel owl-themes active">
        {% for property in properties %}
        <div class="item">
{#            check item active class#}
            <img src="{{ asset('/uploads/' ~ property.pictures.first.filename) }}" alt="gallery-img" style="height: 844px;">
            <div class="container">
                <div class="detail-box">
                    <div class="text-box wow fadeIn" data-wow-delay="400ms">
                        <p class="subheading"><span></span>{{ settings.landingTitle }}</p>
                        <h2 class="heading">{{ property.title }} <br/>  </h2>
                        {% set rawtext = property.description|raw %}
                        {% set text = rawtext|length > 500 ? rawtext|slice(0, 500) ~ '...' : rawtext %}
                        <p class="text">{{ text|raw }}</p>
                        <div class="button-center">
                            <a class="btn button btn-rounded green-btn btn-hvr-blue scroll"  href="#contact">
                                Book Room Now
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {%  endfor %}
    </div>
    <!-- Carousel End -->
    <div class="icons d-flex ">
        <i class="lni lni-chevron-left customPrevBtn"></i>
        <i class="lni lni-chevron-right customNextBtn"></i>
    </div>
</section>
<!-- Gallery Section End -->

templates/front/section/_propertylist.html.twig
<!-- Destination Section Start -->
<section class="destination-section" id="destinations">
    <div class="container">
        <div class="row no-gutters row-1">
            <div class="col-lg-12 col-md-12 col-sm-12 text-center wow fadeInDown" data-wow-delay="400ms">
                <h2 class="heading">Explore Our <br><span>Luxuries Properties</span></h2>
                <p class="subheading">click on a listing to get more details</p>
            </div>
        </div>
        <!-- Row-2 Start -->
        <div class="row">
            {%  for property in properties %}
            <div class="col-lg-4 col-md-12 col-sm-12 destination wow fadeInDown" data-wow-delay="400ms">
                <a class="card" href="{{ path('front_property_show',{'id':property.id}) }}" >
                    <img src="{{ asset('/uploads/' ~ property.mainPicture.filename) }}"  alt="destination-img" style="width:347px">
                    <div class="card-body">
                        <h5 class="card-title">{{ property.title }} <span></span></h5>

{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fas fa-star-half-alt half-checked"></span>#}
                        {% if searchDates|length > 0 %}
                            {% set rates = property.priceList %}
                            {% set sum = 0 %}
                            {%  for rate in rates %}
                                {%  set sum = sum + rate %}
                            {% endfor %}
                            <div class="card-text">
                                {{ rates|length }} nights - {{ sum|format_currency(settings.currency, {fraction_digit: 0}) }}
                            </div>
                        {%  else %}
                            <div class="card-text">
                                <span>From {{ property.minPrice|format_currency(settings.currency, {fraction_digit: 0})}} / night </span>
                            </div>
                        {% endif %}

                    </div>
                </a>
            </div>
            {% endfor %}
{#            {{ dump(properties) }}#}
        </div>
        <!-- Row-3 Start -->
{#        <div class="row row-3">#}
{#            <div class="col-lg-4 col-md-12 col-sm-12 wow fadeInDown" data-wow-delay="400ms">#}
{#                <a class="card" href="travelling/destinations.html">#}
{#                    <img src="travelling/img/destination-4.jpg"  alt="destination-img">#}
{#                    <div class="card-body">#}
{#                        <h5 class="card-title">Malan 103 <span>$5500</span></h5>#}
{#                        <div class="card-text">#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fas fa-star-half-alt half-checked"></span>#}
{#                        </div>#}
{#                    </div>#}
{#                </a>#}
{#            </div>#}
{#            <div class="col-lg-4 col-md-12 col-sm-12 wow fadeInUp" data-wow-delay="400ms">#}
{#                <a class="card" href="#.">#}
{#                    <img src="travelling/img/destination-5.jpg"  alt="destination-img">#}
{#                    <div class="card-body">#}
{#                        <h5 class="card-title">New York 143 <span>$2835</span></h5>#}
{#                        <div class="card-text">#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fas fa-star-half-alt half-checked"></span>#}
{#                        </div>#}
{#                    </div>#}
{#                </a>#}
{#            </div>#}
{#            <div class="col-lg-4 col-md-12 col-sm-12 wow fadeInDown" data-wow-delay="400ms">#}
{#                <a class="card" href="travelling/destinations.html">#}
{#                    <img src="travelling/img/destination-6.jpg"  alt="destination-img">#}
{#                    <div class="card-body">#}
{#                        <h5 class="card-title">Toronto 156 <span>$8000</span></h5>#}
{#                        <div class="card-text">#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fa fa-star checked"></span>#}
{#                            <span class="fas fa-star-half-alt half-checked"></span>#}
{#                        </div>#}
{#                    </div>#}
{#                </a>#}
{#            </div>#}
{#        </div>#}
        <!-- Button Start -->
{#        <div class="button-center wow fadeInUp" data-wow-delay="400ms">#}
{#            <a class="btn button btn-rounded green-btn btn-hvr-blue "  href="travelling/destinations.html">#}
{#                View All Similar Destinations#}
{#            </a>#}
{#        </div>#}
    </div>
    <!-- Container End -->
</section>
<!-- Destination Section End -->

templates/front/section/_slider.html.twig
<!--Slider Section Start-->
<section class="slider-area position-relative" id="home">
    <div class="slider-overlay">
        <div class="container">
            <div class="row ">
                <div class="col-lg-12 text-center text-area wow fadeInDown" data-wow-delay="1000ms">
                    <h5 class="subheading"></h5>
                    <h2 class="heading">{{ settings.landingTitle }}</h2>
                    <p class="text">{{ settings.landingText }}</p>
                </div>
                <!-- </div> -->
            </div>
        </div>
        <!-- Container End -->
    </div>
    <div class="social-icons">
        <ul class="slider-social wow fadeInRight" data-wow-delay="1000ms">
            {% if settings.socialFB is not null %}
            <li><a class="icon-hover wow" href="{{ settings.socialFB }}">
                    <i class="fab fa-facebook-f"></i></a>
            </li>
            {%  endif %}
            {% if settings.socialTwitter is not null %}
            <li><a class="icon-hover" href="{{ settings.socialTwitter }}">
                    <i class="fab fa-twitter"></i></a>
            </li>
            {%  endif %}
            {% if settings.socialLinkedIn is not null %}
            <li><a class="icon-hover" href="{{ settings.socialLinkedIn }}">
                    <i class="fab fa-linkedin-in"></i></a>
            </li>
            {%  endif %}
            {% if settings.socialInsta is not null %}
            <li><a class="icon-hover" href="{{ settings.socialInsta }}">
                    <i class="fab fa-instagram"></i></a>
            </li>
            {% endif %}
        </ul>
    </div>
    <div class="text-center slider-carousel owl-carousel owl-themes active">
        {% for picture in settings.landingSliderPicture %}
        <div class="item active"><img src="{{ asset('/uploads/' ~ picture.filename) }}" alt="slider-img"></div>
        {%  endfor %}
    </div>

</section>
<!-- Slider Section End -->

templates/front/section/_sliderform.html.twig
<!--Slider form start-->
<div class="slider-form">
    <div class="container">
        <div class="row">
            <div class="col-12 wow fadeInUp" data-wow-delay="1000ms">
{#                {{ form_start(availability_form,{'attr':{'class':'row contact-form rounded-pill link'}}) }}#}
{#                <div class="col-12 col-lg-9 d-inline-block d-lg-flex align-items-center">#}
{#                    <div class="form-group">#}
{#                        <label for="availability_start_date"> <span class="fas fa-calendar-plus " aria-hidden="true"></span></label>#}
{#                        {{ form_widget(availability_form.start_date,{'attr':{'placeholder':'Check In'}}) }}#}
{#                    </div>#}
{#                    #}{#                {{ form_widget(availability_form) }}#}
{#                </div>#}
{#                {{ form_errors(availability_form) }}#}
{#                <button class="btn" type="submit" >{{ button_label|default('Save') }}</button>#}
{#                {{ form_end(availability_form) }}#}
{#                <form class="row contact-form rounded-pill link" method="post" name="availability">#}
                {{ form_start(availability_form,{'attr':{'class':'row contact-form rounded-pill link'}}) }}
                    <div class="col-12 col-lg-9">
                        {{ form_errors(availability_form.start_date,{'attr':{'class':'form-control text-danger'}}) }}
                        {{ form_errors(availability_form.end_date,{'attr':{'class':'form-control text-danger'}}) }}
                    </div>
                    <div class="col-12 col-lg-9 d-inline-block d-lg-flex align-items-center">
                        <div class="form-group">
                            <label for="availability_start_date"> <span class="fas fa-calendar-plus " aria-hidden="true"></span></label>
{#                            <input type="text" name='datepicker' class="form-control"  value="" id="datepicker"#}
{#                                   required="" placeholder="Check In" >#}
                            {{ form_widget(availability_form.start_date,{'attr':{'placeholder':'Check In'}}) }}
                        </div>
                        <div class="form-group">
                            <label for="availability_end_date"> <span class="fas fa-calendar-minus " aria-hidden="true"></span></label>
                            {#                            <input type="text" name='datepicker' class="form-control"  value="" id="datepicker"#}
                            {#                                   required="" placeholder="Check In" >#}
                            {{ form_widget(availability_form.end_date,{'attr':{'placeholder':'Check Out'}}) }}
                        </div>
{#                        <div class="form-group ">#}
{#                            <label for="datepickr"> <span class="fas fa-calendar-minus" aria-hidden="true"></span></label>#}
{#                            <input type="text" name='datepickr' class="form-control"  value="" id="datepickr"#}
{#                                   required="" placeholder="Check Out" >#}
{#                        </div>#}
                        <div class="form-group ">
                            <label><i class="fa fa-user mr-2" aria-hidden="true"></i></label>
{#                            <select id="inputStates" class="form-control">#}
{#                                <option class="red">Guests</option>#}
{#                                <option>...</option>#}
{#                            </select>#}
                            {{ form_widget(availability_form.nb_guest,{'attr':{'placeholder':'Guests'}}) }}
                        </div>
{#                        <div class="form-group">#}
{#                            <label><i class="fas fa-users mr-2"  aria-hidden="true"></i></label>#}
{#                            <select id="inputState"  class="form-control">#}
{#                                <option>Children</option>#}
{#                                <option>...</option>#}
{#                            </select>#}
{#                        </div>#}
{#                        <div class="form-group">#}
{#                            <label><i class="fas fa-map-marker " aria-hidden="true"></i></label>#}
{#                            <input type="text" name="Location" placeholder="Location" id="location" required="" class="form-control">#}
{#                        </div>#}
                    </div>
                    <div class="col-12 col-lg-3 ">
                        <button class="btn button btn-rounded green-btn btn-hvr-grey" type="submit">{{ button_label|default('Find') }}
                        </button>
                    </div>
                {{ form_end(availability_form) }}

            </div>
        </div>
    </div>
</div>
<!--Slider form end-->